name: Continuous Integration
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  clientTest:
    name: Frontend Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Run yarn
        working-directory: ./client
        run: yarn
      - name: Run yarn test
        working-directory: ./client
        run: yarn test:ci
  serverTest:
    name: Backend Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17-ea'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        working-directory: ./server
        run: ./gradlew build
 